// Generated by BUCKLESCRIPT VERSION 1.7.2, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("../src/json_decode.js");

function point(json) {
  return /* float array */[
          Json_decode.field("x", Json_decode.$$float, json),
          Json_decode.field("y", Json_decode.$$float, json)
        ];
}

function line(json) {
  return /* record */[
          /* start */Json_decode.field("start", point, json),
          /* end_ */Json_decode.field("end", point, json),
          /* thickness */Json_decode.optional(function (param) {
                return Json_decode.field("thickness", Json_decode.$$int, param);
              }, json)
        ];
}

var Decode = /* module */[
  /* point */point,
  /* line */line
];

var data = " {\n  \"start\": { \"x\": 1.1, \"y\": -0.4 },\n  \"end\":   { \"x\": 5.3, \"y\": 3.8 }\n} ";

console.log(line(JSON.parse(data)));

exports.Decode = Decode;
exports.data   = data;
/*  Not a pure module */
